### ISSUE TITLE
PD: feedback

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#12]
Very good and clear https://github.com/openclimatefix/pvsite-datamodel/blob/main/sdk/pvsite-python/write.py#L92

- would be good to pass the forecast_version as an optional variable
- should we add a row make sure there is only one target time per forecast, or at list a logger warning
- good to rename `df`, should be something like `all_forecasts_df`

**Comment by devsjc** [comment]
Is it the case then that one forecast is for a single site at a single target time? If that is the case, surely better than passing a dataframe where two columns contain the same data in every row is just passing a list of forecast values, along with an individual target time and a pv_uuid?

**Comment by devsjc** [comment]
So this
```python
# Filter the forecasted values by target_time
```
needs to happen before I create the forecast?

**Comment by peterdudfield** [comment]
nah could just happen just before 103. Just to make sure all `target_times_utc` are unique.

**Comment by devsjc** [comment]
Sorry I'm not keeping up here:

Is what you're saying:
1. Split the table up by sites
2. Create a new forecast object for that site
3. (New) Check that all the forecast value entries the table for that site have the same target_time_utc
4.  (Change) Make a datetime interval if not exists for this site (instead of one datetime interval per unique target time in this site's dataframe subset, as they should all have the same target time) OR print a log if there is more than one unique target_time
5. Create a forecast value for each entry in the subset

Does that seem right?

**Comment by peterdudfield** [comment]
3. (New) Check that all the forecast value entries for that site have a unique target_time_utc

**Comment by peterdudfield** [comment]
SOmehting like 
```
assert len(df_site) == len(df_site["target_datetime_utc"].unique())
```
Or it could just be a warning, if this is not true

**Comment by devsjc** [comment]
Ah so you're saying there shouldn't be any duplicate target times per forecast per site?

**Comment by devsjc** [comment]
Like this https://github.com/openclimatefix/pvsite-datamodel/commit/224ce40fcffd1cfbbe40d0806a3933ff2e9c68d3

**Comment by peterdudfield** [comment]
perfect

> Like this [224ce40](https://github.com/openclimatefix/pvsite-datamodel/commit/224ce40fcffd1cfbbe40d0806a3933ff2e9c68d3)

perfect

**Comment by devsjc** [comment]
Ah sorry, missed that - updated in https://github.com/openclimatefix/pvsite-datamodel/commit/85a9b3da9104fcf2085b07b709ea362274337079
